### ISSUE TITLE
能提供一下权重的百度网盘地址吗？

### ISSUE THREAD

**Issue by ulanbator** [whai362/AE_TextSpotter#3]
不能墙，所以不能用谷歌网盘。

**Comment by whai362** [comment]
bert-base-chinese.zip 链接: https://pan.baidu.com/s/1QHhSdWC1dOkgHuu5M4ne7g  密码: hg4k
rects_ae_textspotter_lm_r50_1x.pth 链接: https://pan.baidu.com/s/1FGrL4MOjlwqPrE4L3PgHkA  密码: tijn
