### ISSUE TITLE
subprocess.CalledProcessError&KeyError: 'ReCTSDataset is not in the dataset registry'

### ISSUE THREAD

**Issue by ulanbator** [whai362/AE_TextSpotter#5]
下载好网络训练好的权重，
使用命令：
tools/rects_dist_test.sh local_configs/rects_ae_textspotter_lm_r50_1x.py work_dirs/rects_ae_textspotter_lm_r50_1x/latest.pth 8 --json_out results.json测试TDA-ReCTS的测试集
报错信息：
Traceback (most recent call last):
  File "tools/rects_test.py", line 276, in <module>
    main()
  File "tools/rects_test.py", line 243, in main
    dataset = build_dataset(cfg.data.test)
  File "/home/fangzheng/iflytek_project/AE_TextSpotter/mmdetection/mmdet/datasets/builder.py", line 71, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/fangzheng/anaconda3/envs/AET/lib/python3.6/site-packages/mmcv/utils/registry.py", line 164, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'ReCTSDataset is not in the dataset registry'

subprocess.CalledProcessError: Command '['/home/fangzheng/anaconda3/envs/AET/bin/python', '-u', 'tools/rects_test.py', '--local_rank=7', 'local_configs/rects_ae_textspotter_lm_r50_1x.py', 'work_dirs/rects_ae_textspotter_lm_r50_1x/latest.pth', '--launcher', 'pytorch', '--json_out', 'results.json']' returned non-zero exit status 1.
--json_out results.json

是不是我的训练数据集没有上传完整的原因，但是我测试好像也用不到训练集吧：

![项目结构](https://user-images.githubusercontent.com/26237152/96963778-da9e6700-153b-11eb-9ef2-fa201c436460.png)
![报错信息](https://user-images.githubusercontent.com/26237152/96963790-e0944800-153b-11eb-9348-a2264f9df89c.png)

**Comment by ulanbator** [comment]
能否提供一下代码的开发环境比如CUDA、CUDNN等，调试代码会有“cannot import name 'deform_conv_cuda'”报错

**Comment by whai362** [comment]
我用的CUDA 9.0
可能是mmdetection没有编译成功。
你要先执行“pip install -v -e . --user”进行编译。
请仔细看https://github.com/open-mmlab/mmdetection/blob/v1.0rc1/docs/INSTALL.md 里面的安装步骤。
如果mmdetection v1.0rc1能运行，我这份代码也应该没有问题。
